[package]
name = "egui-android-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type=["cdylib"]

[dependencies]
log = "0.4"
android_logger = "0.13"
eframe = { version = "0.24", features = [ "wgpu", "android-native-activity" ] }
egui_demo_lib = "0.24"

# Used to get same winit used by eframe.
egui-winit = { version = "0.24", default-features = false, features = [
        "clipboard",
        "links",
] }
