[package]
name = "egui-android-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
android_logger = "0.13"
android-activity = { version="0.5", features = [ "native-activity" ] }

[lib]
crate_type=["cdylib"]
